name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install tox and any other packages
        run: pip install django
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        #cd budgetproject && python3 manage.py test budget
        #eed312912caa4f78c2b946faf2b21720d34e3888
        #ff0c9dcc5d11fbbdcebe681dda56ff34798344e8
        run: |
          git bisect start
          git bisect bad eed3129
          git bisect good ff0c9dc
          git bisect run sh test.sh
          git bisect reset